{
 "title": "EventHub Consumer",
 "description": "Default metrics emitted by Micrometer for GC, Memory, Threads, CPU usage, etc.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Consumer - Aggregate based Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Σ (events / sec) ∀ partitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(ehconsumer_events_received_total{app=\"eventhub-consumer\"}[1m]))",
       "legendFormat": "{{partitionId}}"
      }
     ]
    },
    {
     "title": "Σ Lag ∀ partitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ehconsumer_lag{app=\"eventhub-consumer\"})",
       "legendFormat": "{{partitionId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer - Partition based metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "events received / partition / sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(ehconsumer_events_received_total{app=\"eventhub-consumer\"}[1m])) by (partitionId)",
       "legendFormat": "{{partitionId}}"
      }
     ]
    },
    {
     "title": "lag / partition",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ehconsumer_lag{app=\"eventhub-consumer\"}) by (partitionId)",
       "legendFormat": "{{partitionId}}"
      }
     ]
    },
    {
     "title": "initializations / partition / sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(ehconsumer_partition_initialization_total{app=\"eventhub-consumer\"}[1m])) by (partitionId)",
       "legendFormat": "{{partitionId}}"
      }
     ]
    },
    {
     "title": "Approx last message processed time / partition",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "ehconsumer_event_timestamp{app=\"eventhub-consumer\"}",
       "legendFormat": "{{partitionId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pause: End of Minor GC",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{action=\"end of minor GC\"}[1m]) / rate(jvm_gc_pause_seconds_count{action=\"end of minor GC\"}[1m])",
       "legendFormat": "avg: {{cause}}"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{action=\"end of minor GC\"}",
       "legendFormat": "max: {{cause}}"
      }
     ]
    },
    {
     "title": "End of minor GC Triggers / sec",
     "type": "graph",
     "description": "#times minor gc was triggered / sec",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{action=\"end of minor GC\"}[1m])",
       "legendFormat": "{{cause}}"
      }
     ]
    },
    {
     "title": "GC: Live Data Size",
     "type": "graph",
     "description": "Size of long-lived heap memory pool after reclamation",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "jvm_gc_live_data_size_bytes", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "GC Pause: End of Major GC",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{action=\"end of major GC\"}[1m]) / rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[1m])",
       "legendFormat": "avg: {{cause}}"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{action=\"end of major GC\"}",
       "legendFormat": "max: {{cause}}"
      }
     ]
    },
    {
     "title": "Major GC Triggers / sec",
     "type": "graph",
     "description": "#times major gc was triggered / sec",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[1m])",
       "legendFormat": "{{cause}}"
      }
     ]
    },
    {
     "title": "GC: Max Size of long lived memory pool",
     "type": "graph",
     "description": "Max size of long-lived heap memory pool",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "jvm_gc_max_data_size_bytes", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "GC: Allocated Memory / sec",
     "type": "graph",
     "description": "Incremented for an increase in the size of the (young) heap memory pool after one GC to before the next",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC: Promoted Memory / sec",
     "type": "graph",
     "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logback",
     "type": "graph",
     "description": "Number of error level events that made it to the logs",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(logback_events_total[1m])", "legendFormat": "{{level}}" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap: Used Memory",
     "type": "graph",
     "description": "The amount of used memory",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Heap: Committed Memory",
     "type": "graph",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Heap: Max Memory",
     "type": "graph",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "NonHeap: Used Memory",
     "type": "graph",
     "description": "The amount of used memory",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "NonHeap: Committed Memory",
     "type": "graph",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{area=\"nonheap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "NonHeap: Max Memory",
     "type": "graph",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{area=\"nonheap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer: Used Memory",
     "type": "graph",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Buffer: Total Capacity",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity_bytes",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer: Count",
     "type": "graph",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_buffer_count_buffers", "legendFormat": "{{id}}" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread States",
     "type": "graph",
     "description": "The current number of threads having NEW state",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_states_threads", "legendFormat": "{{state}}" }
     ]
    },
    {
     "title": "Live Threads",
     "type": "graph",
     "description": "The current number of live threads including both daemon and non-daemon threads",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_live_threads", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Daemon Threads",
     "type": "graph",
     "description": "The current number of live daemon threads",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_daemon_threads", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Peak Threads",
     "type": "graph",
     "description": "The peak live thread count since the Java virtual machine started or peak was reset",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_peak_threads", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "JVM Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "graph",
     "description": "The \"recent cpu usage\" for the Java Virtual Machine process",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "process_cpu_usage", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Open files count",
     "type": "graph",
     "description": "The open file descriptor count",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "process_files_open_files", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "System CPU Usage",
     "type": "graph",
     "description": "The \"recent cpu usage\" for the whole system",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "system_cpu_usage", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "System Load Average",
     "type": "graph",
     "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "system_load_average_1m", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Class",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loaded classes",
     "type": "graph",
     "description": "The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_classes_loaded_classes", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Unloaded classes / sec",
     "type": "graph",
     "description": "The number of classes unloaded / sec since the Java virtual machine has started execution",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_classes_unloaded_classes_total[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}