{
 "title": "Vector",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vector Buffer Event Size / component_id / buffer_type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (component_id, buffer_type) (vector_buffer_events)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Component Errors / component_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Utilization / component_id",
   "type": "timeseries",
   "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (component_id) (vector_utilization)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Component Discarded Events / component_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_discarded_events_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Component Events + Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vector Events (Received - Sent) / component_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_events_total[1m])) - sum by (component_id) (rate(vector_component_sent_events_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vector Events (Received - Sent) Bytes / component_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_event_bytes_total[1m])) - sum by (component_id) (rate(vector_component_sent_event_bytes_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vector Events Received / component_id",
     "type": "timeseries",
     "description": "The number of events accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_events_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vector Events Sent / component_id",
     "type": "timeseries",
     "description": "The total number of events emitted by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_sent_events_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vector Events Received Bytes / component_id",
     "type": "timeseries",
     "description": "The number of event bytes accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_event_bytes_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vector Events Sent Bytes / component_id",
     "type": "timeseries",
     "description": "The total number of event bytes emitted by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_sent_event_bytes_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vector Received Bytes / component_id",
     "type": "timeseries",
     "description": "The number of raw bytes accepted by this component from source origins.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_received_bytes_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vector Sent Bytes / component_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (component_id) (rate(vector_component_sent_bytes_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}